version: "3"
services:
  selenium-hub:
    image: "selenium/hub"
    ports:
      - 4444:4444
    networks:
      - grid_bridge
  
  selenium-node-firefox:
    image: "selenium/node-firefox"
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: selenium-hub
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_NODE_MAX_SESSIONS: 10
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_VNC_NO_PASSWORD: 1
      JAVA_OPTS: -Dwebdriver.chrome.whitelistedIps=
    depends_on:
      - selenium-hub
    networks:
      - grid_bridge

  test-container:
    image: simbirsoft_test
    environment:
      HUB_HOST: selenium-hub
      REPORTS_PATH: /data/reports
      EXPORT_PATH: /data/export
    depends_on:
      - selenium-hub
    volumes:
      - ${SIMBIRSOFT_APP_DATA_PATH}:/data
    networks:
      - grid_bridge
  
  report-container:
    image: simbirsoft_report
    volumes:
      - ${SIMBIRSOFT_APP_DATA_PATH}:/data
    environment:
      REPORTS_PATH: /data/reports
    ports:
      - 9000:9000
    networks:
      - report_bridge

networks:
  grid_bridge:
    driver: bridge
  report_bridge:
    driver: bridge